import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:phosphoricons_flutter/phosphoricons_flutter.dart';

/// Semantic icons used by Nebu.
///
/// Screens describe intent instead of choosing an icon family. The resolver
/// renders Cupertino glyphs on iOS, Material glyphs on Android, and Phosphor
/// glyphs on Web. Other native platforms use Material as a safe fallback.
enum AdaptiveIconSymbol {
  back,
  forward,
  home,
  toys,
  activity,
  profile,
  settings,
  add,
  search,
  close,
  check,
  success,
  info,
  warning,
  error,
  refresh,
  edit,
  delete,
  mail,
  phone,
  chat,
  help,
  language,
  darkMode,
  privacy,
  document,
  login,
  person,
  people,
  child,
  lock,
  visible,
  hidden,
  bluetooth,
  bluetoothOff,
  bluetoothSearching,
  wifi,
  wifiOff,
  microphone,
  microphoneOff,
  volumeHigh,
  volumeLow,
  volumeOff,
  robot,
  sparkle,
  book,
  time,
  notifications,
  camera,
  photo,
  link,
  unlink,
  qrCode,
  download,
  send,
  play,
  calendar,
  key,
  location,
  device,
  battery,
  signalHigh,
  signalMedium,
  signalLow,
  shield,
  label,
}

enum AdaptiveIconPlatform { ios, android, web }

extension AdaptiveIconResolver on AdaptiveIconSymbol {
  AdaptiveIconPlatform get currentPlatform {
    if (kIsWeb) {
      return AdaptiveIconPlatform.web;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return AdaptiveIconPlatform.ios;
    }
    return AdaptiveIconPlatform.android;
  }

  IconData get iconData => resolveFor(currentPlatform);

  /// Public to keep platform mappings deterministic and unit-testable.
  IconData resolveFor(AdaptiveIconPlatform platform) => switch (platform) {
    AdaptiveIconPlatform.ios => _cupertino,
    AdaptiveIconPlatform.android => _material,
    AdaptiveIconPlatform.web => _phosphor,
  };

  IconData get _material => switch (this) {
    AdaptiveIconSymbol.back => Icons.arrow_back_ios_new_rounded,
    AdaptiveIconSymbol.forward => Icons.arrow_forward_ios_rounded,
    AdaptiveIconSymbol.home => Icons.home_outlined,
    AdaptiveIconSymbol.toys => Icons.dashboard_outlined,
    AdaptiveIconSymbol.activity => Icons.history,
    AdaptiveIconSymbol.profile => Icons.person_outline_rounded,
    AdaptiveIconSymbol.settings => Icons.settings_outlined,
    AdaptiveIconSymbol.add => Icons.add_rounded,
    AdaptiveIconSymbol.search => Icons.search_rounded,
    AdaptiveIconSymbol.close => Icons.close_rounded,
    AdaptiveIconSymbol.check => Icons.check_rounded,
    AdaptiveIconSymbol.success => Icons.check_circle_outline_rounded,
    AdaptiveIconSymbol.info => Icons.info_outline_rounded,
    AdaptiveIconSymbol.warning => Icons.warning_amber_rounded,
    AdaptiveIconSymbol.error => Icons.error_outline_rounded,
    AdaptiveIconSymbol.refresh => Icons.refresh_rounded,
    AdaptiveIconSymbol.edit => Icons.edit_outlined,
    AdaptiveIconSymbol.delete => Icons.delete_outline_rounded,
    AdaptiveIconSymbol.mail => Icons.mail_outline_rounded,
    AdaptiveIconSymbol.phone => Icons.phone_outlined,
    AdaptiveIconSymbol.chat => Icons.chat_bubble_outline_rounded,
    AdaptiveIconSymbol.help => Icons.help_outline_rounded,
    AdaptiveIconSymbol.language => Icons.language_outlined,
    AdaptiveIconSymbol.darkMode => Icons.dark_mode_outlined,
    AdaptiveIconSymbol.privacy => Icons.privacy_tip_outlined,
    AdaptiveIconSymbol.document => Icons.description_outlined,
    AdaptiveIconSymbol.login => Icons.login_rounded,
    AdaptiveIconSymbol.person => Icons.person_outline_rounded,
    AdaptiveIconSymbol.people => Icons.people_outline_rounded,
    AdaptiveIconSymbol.child => Icons.child_care_outlined,
    AdaptiveIconSymbol.lock => Icons.lock_outline_rounded,
    AdaptiveIconSymbol.visible => Icons.visibility_outlined,
    AdaptiveIconSymbol.hidden => Icons.visibility_off_outlined,
    AdaptiveIconSymbol.bluetooth => Icons.bluetooth_rounded,
    AdaptiveIconSymbol.bluetoothOff => Icons.bluetooth_disabled_rounded,
    AdaptiveIconSymbol.bluetoothSearching => Icons.bluetooth_searching_rounded,
    AdaptiveIconSymbol.wifi => Icons.wifi_rounded,
    AdaptiveIconSymbol.wifiOff => Icons.wifi_off_rounded,
    AdaptiveIconSymbol.microphone => Icons.mic_none_rounded,
    AdaptiveIconSymbol.microphoneOff => Icons.mic_off_outlined,
    AdaptiveIconSymbol.volumeHigh => Icons.volume_up_outlined,
    AdaptiveIconSymbol.volumeLow => Icons.volume_down_outlined,
    AdaptiveIconSymbol.volumeOff => Icons.volume_off_outlined,
    AdaptiveIconSymbol.robot => Icons.smart_toy_outlined,
    AdaptiveIconSymbol.sparkle => Icons.auto_awesome_outlined,
    AdaptiveIconSymbol.book => Icons.menu_book_outlined,
    AdaptiveIconSymbol.time => Icons.timer_outlined,
    AdaptiveIconSymbol.notifications => Icons.notifications_none_rounded,
    AdaptiveIconSymbol.camera => Icons.camera_alt_outlined,
    AdaptiveIconSymbol.photo => Icons.photo_library_outlined,
    AdaptiveIconSymbol.link => Icons.link_rounded,
    AdaptiveIconSymbol.unlink => Icons.link_off_rounded,
    AdaptiveIconSymbol.qrCode => Icons.qr_code_scanner_rounded,
    AdaptiveIconSymbol.download => Icons.download_outlined,
    AdaptiveIconSymbol.send => Icons.send_outlined,
    AdaptiveIconSymbol.play => Icons.play_circle_outline_rounded,
    AdaptiveIconSymbol.calendar => Icons.calendar_month_outlined,
    AdaptiveIconSymbol.key => Icons.key_outlined,
    AdaptiveIconSymbol.location => Icons.location_on_outlined,
    AdaptiveIconSymbol.device => Icons.phone_android_outlined,
    AdaptiveIconSymbol.battery => Icons.battery_std_outlined,
    AdaptiveIconSymbol.signalHigh => Icons.signal_cellular_4_bar_rounded,
    AdaptiveIconSymbol.signalMedium => Icons.signal_cellular_alt_rounded,
    AdaptiveIconSymbol.signalLow => Icons.signal_cellular_alt_1_bar_rounded,
    AdaptiveIconSymbol.shield => Icons.security_outlined,
    AdaptiveIconSymbol.label => Icons.label_outline_rounded,
  };

  IconData get _cupertino => switch (this) {
    AdaptiveIconSymbol.back => CupertinoIcons.back,
    AdaptiveIconSymbol.forward => CupertinoIcons.forward,
    AdaptiveIconSymbol.home => CupertinoIcons.home,
    AdaptiveIconSymbol.toys => CupertinoIcons.square_grid_2x2,
    AdaptiveIconSymbol.activity => CupertinoIcons.arrow_counterclockwise,
    AdaptiveIconSymbol.profile => CupertinoIcons.person_crop_circle,
    AdaptiveIconSymbol.settings => CupertinoIcons.gear,
    AdaptiveIconSymbol.add => CupertinoIcons.add,
    AdaptiveIconSymbol.search => CupertinoIcons.search,
    AdaptiveIconSymbol.close => CupertinoIcons.clear,
    AdaptiveIconSymbol.check => CupertinoIcons.check_mark,
    AdaptiveIconSymbol.success => CupertinoIcons.check_mark_circled,
    AdaptiveIconSymbol.info => CupertinoIcons.info,
    AdaptiveIconSymbol.warning => CupertinoIcons.exclamationmark_triangle,
    AdaptiveIconSymbol.error => CupertinoIcons.exclamationmark_circle,
    AdaptiveIconSymbol.refresh => CupertinoIcons.refresh,
    AdaptiveIconSymbol.edit => CupertinoIcons.pencil,
    AdaptiveIconSymbol.delete => CupertinoIcons.trash,
    AdaptiveIconSymbol.mail => CupertinoIcons.mail,
    AdaptiveIconSymbol.phone => CupertinoIcons.phone,
    AdaptiveIconSymbol.chat => CupertinoIcons.chat_bubble,
    AdaptiveIconSymbol.help => CupertinoIcons.question_circle,
    AdaptiveIconSymbol.language => CupertinoIcons.globe,
    AdaptiveIconSymbol.darkMode => CupertinoIcons.moon,
    AdaptiveIconSymbol.privacy => CupertinoIcons.shield,
    AdaptiveIconSymbol.document => CupertinoIcons.doc_text,
    AdaptiveIconSymbol.login => CupertinoIcons.arrow_right_square,
    AdaptiveIconSymbol.person => CupertinoIcons.person,
    AdaptiveIconSymbol.people => CupertinoIcons.person_2,
    AdaptiveIconSymbol.child => CupertinoIcons.person_crop_circle,
    AdaptiveIconSymbol.lock => CupertinoIcons.lock,
    AdaptiveIconSymbol.visible => CupertinoIcons.eye,
    AdaptiveIconSymbol.hidden => CupertinoIcons.eye_slash,
    AdaptiveIconSymbol.bluetooth => CupertinoIcons.bluetooth,
    AdaptiveIconSymbol.bluetoothOff => CupertinoIcons.bluetooth,
    AdaptiveIconSymbol.bluetoothSearching => CupertinoIcons.bluetooth,
    AdaptiveIconSymbol.wifi => CupertinoIcons.wifi,
    AdaptiveIconSymbol.wifiOff => CupertinoIcons.wifi,
    AdaptiveIconSymbol.microphone => CupertinoIcons.mic,
    AdaptiveIconSymbol.microphoneOff => CupertinoIcons.mic,
    AdaptiveIconSymbol.volumeHigh => CupertinoIcons.speaker_3,
    AdaptiveIconSymbol.volumeLow => CupertinoIcons.speaker_1,
    AdaptiveIconSymbol.volumeOff => CupertinoIcons.speaker_slash,
    AdaptiveIconSymbol.robot => CupertinoIcons.device_phone_portrait,
    AdaptiveIconSymbol.sparkle => CupertinoIcons.sparkles,
    AdaptiveIconSymbol.book => CupertinoIcons.book,
    AdaptiveIconSymbol.time => CupertinoIcons.time,
    AdaptiveIconSymbol.notifications => CupertinoIcons.bell,
    AdaptiveIconSymbol.camera => CupertinoIcons.camera,
    AdaptiveIconSymbol.photo => CupertinoIcons.photo,
    AdaptiveIconSymbol.link => CupertinoIcons.link,
    AdaptiveIconSymbol.unlink => CupertinoIcons.link,
    AdaptiveIconSymbol.qrCode => CupertinoIcons.qrcode,
    AdaptiveIconSymbol.download => CupertinoIcons.arrow_down_to_line,
    AdaptiveIconSymbol.send => CupertinoIcons.paperplane,
    AdaptiveIconSymbol.play => CupertinoIcons.play_circle,
    AdaptiveIconSymbol.calendar => CupertinoIcons.calendar,
    AdaptiveIconSymbol.key => CupertinoIcons.lock,
    AdaptiveIconSymbol.location => CupertinoIcons.location,
    AdaptiveIconSymbol.device => CupertinoIcons.device_phone_portrait,
    AdaptiveIconSymbol.battery => CupertinoIcons.battery_100,
    AdaptiveIconSymbol.signalHigh ||
    AdaptiveIconSymbol.signalMedium ||
    AdaptiveIconSymbol.signalLow =>
      CupertinoIcons.antenna_radiowaves_left_right,
    AdaptiveIconSymbol.shield => CupertinoIcons.shield,
    AdaptiveIconSymbol.label => CupertinoIcons.tag,
  };

  IconData get _phosphor => switch (this) {
    AdaptiveIconSymbol.back => PhosphorIconsRegular.caretLeft,
    AdaptiveIconSymbol.forward => PhosphorIconsRegular.caretRight,
    AdaptiveIconSymbol.home => PhosphorIconsRegular.house,
    AdaptiveIconSymbol.toys => PhosphorIconsRegular.squaresFour,
    AdaptiveIconSymbol.activity => PhosphorIconsRegular.clockCounterClockwise,
    AdaptiveIconSymbol.profile => PhosphorIconsRegular.userCircle,
    AdaptiveIconSymbol.settings => PhosphorIconsRegular.gear,
    AdaptiveIconSymbol.add => PhosphorIconsRegular.plus,
    AdaptiveIconSymbol.search => PhosphorIconsRegular.magnifyingGlass,
    AdaptiveIconSymbol.close => PhosphorIconsRegular.x,
    AdaptiveIconSymbol.check => PhosphorIconsRegular.check,
    AdaptiveIconSymbol.success => PhosphorIconsRegular.checkCircle,
    AdaptiveIconSymbol.info => PhosphorIconsRegular.info,
    AdaptiveIconSymbol.warning => PhosphorIconsRegular.warning,
    AdaptiveIconSymbol.error => PhosphorIconsRegular.warningCircle,
    AdaptiveIconSymbol.refresh => PhosphorIconsRegular.arrowsClockwise,
    AdaptiveIconSymbol.edit => PhosphorIconsRegular.pencilSimple,
    AdaptiveIconSymbol.delete => PhosphorIconsRegular.trash,
    AdaptiveIconSymbol.mail => PhosphorIconsRegular.envelope,
    AdaptiveIconSymbol.phone => PhosphorIconsRegular.phone,
    AdaptiveIconSymbol.chat => PhosphorIconsRegular.chatCircle,
    AdaptiveIconSymbol.help => PhosphorIconsRegular.question,
    AdaptiveIconSymbol.language => PhosphorIconsRegular.globe,
    AdaptiveIconSymbol.darkMode => PhosphorIconsRegular.moon,
    AdaptiveIconSymbol.privacy => PhosphorIconsRegular.shield,
    AdaptiveIconSymbol.document => PhosphorIconsRegular.fileText,
    AdaptiveIconSymbol.login => PhosphorIconsRegular.signIn,
    AdaptiveIconSymbol.person => PhosphorIconsRegular.user,
    AdaptiveIconSymbol.people => PhosphorIconsRegular.users,
    AdaptiveIconSymbol.child => PhosphorIconsRegular.baby,
    AdaptiveIconSymbol.lock => PhosphorIconsRegular.lock,
    AdaptiveIconSymbol.visible => PhosphorIconsRegular.eye,
    AdaptiveIconSymbol.hidden => PhosphorIconsRegular.eyeSlash,
    AdaptiveIconSymbol.bluetooth => PhosphorIconsRegular.bluetooth,
    AdaptiveIconSymbol.bluetoothOff => PhosphorIconsRegular.bluetoothSlash,
    AdaptiveIconSymbol.bluetoothSearching => PhosphorIconsRegular.bluetooth,
    AdaptiveIconSymbol.wifi => PhosphorIconsRegular.wifiHigh,
    AdaptiveIconSymbol.wifiOff => PhosphorIconsRegular.wifiSlash,
    AdaptiveIconSymbol.microphone => PhosphorIconsRegular.microphone,
    AdaptiveIconSymbol.microphoneOff => PhosphorIconsRegular.microphoneSlash,
    AdaptiveIconSymbol.volumeHigh => PhosphorIconsRegular.speakerHigh,
    AdaptiveIconSymbol.volumeLow => PhosphorIconsRegular.speakerLow,
    AdaptiveIconSymbol.volumeOff => PhosphorIconsRegular.speakerSlash,
    AdaptiveIconSymbol.robot => PhosphorIconsRegular.robot,
    AdaptiveIconSymbol.sparkle => PhosphorIconsRegular.sparkle,
    AdaptiveIconSymbol.book => PhosphorIconsRegular.bookOpen,
    AdaptiveIconSymbol.time => PhosphorIconsRegular.timer,
    AdaptiveIconSymbol.notifications => PhosphorIconsRegular.bell,
    AdaptiveIconSymbol.camera => PhosphorIconsRegular.camera,
    AdaptiveIconSymbol.photo => PhosphorIconsRegular.image,
    AdaptiveIconSymbol.link => PhosphorIconsRegular.link,
    AdaptiveIconSymbol.unlink => PhosphorIconsRegular.linkBreak,
    AdaptiveIconSymbol.qrCode => PhosphorIconsRegular.qrCode,
    AdaptiveIconSymbol.download => PhosphorIconsRegular.downloadSimple,
    AdaptiveIconSymbol.send => PhosphorIconsRegular.paperPlaneTilt,
    AdaptiveIconSymbol.play => PhosphorIconsRegular.playCircle,
    AdaptiveIconSymbol.calendar => PhosphorIconsRegular.calendar,
    AdaptiveIconSymbol.key => PhosphorIconsRegular.key,
    AdaptiveIconSymbol.location => PhosphorIconsRegular.mapPin,
    AdaptiveIconSymbol.device => PhosphorIconsRegular.deviceMobile,
    AdaptiveIconSymbol.battery => PhosphorIconsRegular.batteryHigh,
    AdaptiveIconSymbol.signalHigh => PhosphorIconsRegular.cellSignalHigh,
    AdaptiveIconSymbol.signalMedium => PhosphorIconsRegular.cellSignalMedium,
    AdaptiveIconSymbol.signalLow => PhosphorIconsRegular.cellSignalLow,
    AdaptiveIconSymbol.shield => PhosphorIconsRegular.shieldCheck,
    AdaptiveIconSymbol.label => PhosphorIconsRegular.tag,
  };
}

class AdaptiveIcon extends StatelessWidget {
  const AdaptiveIcon(
    this.symbol, {
    super.key,
    this.size,
    this.color,
    this.semanticLabel,
    this.textDirection,
  });

  final AdaptiveIconSymbol symbol;
  final double? size;
  final Color? color;
  final String? semanticLabel;
  final TextDirection? textDirection;

  @override
  Widget build(BuildContext context) => Icon(
    symbol.iconData,
    size: size,
    color: color,
    semanticLabel: semanticLabel,
    textDirection: textDirection,
  );
}
