// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart' show appFlavor;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return appFlavor == 'dev' ? iosDev : ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB60CngRsi8xx4qrbnQSzx0m3yjcGs4yDU',
    appId: '1:459591254120:web:401f12fdbcb80500a93bdd',
    messagingSenderId: '459591254120',
    projectId: 'flow-nebu-prod',
    authDomain: 'flow-nebu-prod.firebaseapp.com',
    storageBucket: 'flow-nebu-prod.firebasestorage.app',
    measurementId: 'G-4PMRYGEZC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-lvjYHWY8e-FOkr9QUudSE8u_D1nsqc',
    appId: '1:459591254120:android:692beb5bf2da93c7a93bdd',
    messagingSenderId: '459591254120',
    projectId: 'flow-nebu-prod',
    storageBucket: 'flow-nebu-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSNeEC_FNxcAbuMtJpiEMKZOU-hLVUNiE',
    appId: '1:459591254120:ios:c683ef45fbd64f62a93bdd',
    messagingSenderId: '459591254120',
    projectId: 'flow-nebu-prod',
    storageBucket: 'flow-nebu-prod.firebasestorage.app',
    iosBundleId: 'com.nebu.nebuMobileFlutter',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDSNeEC_FNxcAbuMtJpiEMKZOU-hLVUNiE',
    appId: '1:459591254120:ios:202769fc9b91ca60a93bdd',
    messagingSenderId: '459591254120',
    projectId: 'flow-nebu-prod',
    storageBucket: 'flow-nebu-prod.firebasestorage.app',
    iosBundleId: 'com.nebu.nebuMobileFlutter.dev',
  );
}
