// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfF-f6Vj6fxRxTD1gFWcKT58I872P356E',
    appId: '1:874117365573:web:184e47354a9082b1bec82c',
    messagingSenderId: '874117365573',
    projectId: 'nebu-b65d4',
    authDomain: 'nebu-b65d4.firebaseapp.com',
    storageBucket: 'nebu-b65d4.firebasestorage.app',
    measurementId: 'G-85YCDD836T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwiBLWDpC9RikFIhAJwU_yi2va2gJJGPw',
    appId: '1:874117365573:android:723ca9a68be2b591bec82c',
    messagingSenderId: '874117365573',
    projectId: 'nebu-b65d4',
    storageBucket: 'nebu-b65d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8a_PkTUg-XZG0Pw06QZuXDPC44b6Z8g8',
    appId: '1:874117365573:ios:67bd0e8e27189fc8bec82c',
    messagingSenderId: '874117365573',
    projectId: 'nebu-b65d4',
    storageBucket: 'nebu-b65d4.firebasestorage.app',
    iosBundleId: 'com.nebu.nebuMobileFlutter',
  );
}
