enum AppRoutes {
  splash('/'),
  welcome('/welcome'),
  login('/login'),
  signUp('/signup'),
  home('/home'),
  profile('/profile'),
  activityLog('/activity-log'),
  myToys('/my-toys'),
  qrScanner('/qr-scanner'),
  editProfile('/edit-profile'),
  toySettings('/toy-settings'),
  notifications('/notifications'),
  privacySettings('/privacy-settings'),
  privacyPolicy('/privacy-policy'),
  termsOfService('/terms-of-service'),
  helpSupport('/help-support'),
  usageLimits('/usage-limits'),
  connectionSetup('/setup/connection'),
  toyNameSetup('/setup/toy-name'),
  wifiSetup('/setup/wifi'),
  ageSetup('/setup/age'),
  personalitySetup('/setup/personality'),
  voiceSetup('/setup/voice'),
  favoritesSetup('/setup/favorites'),
  worldInfoSetup('/setup/world-info'),
  childProfile('/child-profile'),
  walkieTalkie('/walkie-talkie'),
  toyMemory('/toy-memory'),
  personalities('/personalities'),
  playground('/playground'),
  healthCheck('/health-check'),
  knowledgeSearch('/knowledge-search'),
  voiceHistory('/voice-history'),
  settings('/settings');

  const AppRoutes(this.path);
  final String path;
}
